swagger: '2.0'
info:
  title: API Doc
  description: Swagger API Documentation
  version: 1.0.0
host: localhost
basePath: /
tags: []
schemes:
  - http
consumes: []
produces: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /get-state:
    post:
      security:
        - Bearer: []
      tags: []
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              districtId:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /get-district-list:
    post:
      security:
        - Bearer: []
      tags: []
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              stateId:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /get-state-list:
    get:
      security:
        - Bearer: []
      tags: []
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /user-registration:
    post:
      tags:
        - User
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              firstName:
                example: any
              lastName:
                example: any
              dateOfBirth:
                example: any
              gender:
                example: any
              email:
                example: any
              mobileNo:
                example: any
              preferredLanguage:
                example: any
              district:
                example: any
              pswd:
                example: any
              country:
                example: any
              age:
                example: any
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error 
  /verify-user-email:
    post:
      tags:
        - User
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              email:
                example: any
              otp:
                example: any
              secureId:
                example: any
              captchaText:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /login-user:
    post:
      tags:
        - User
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              email:
                example: any
              password:
                example: any
              secureId:
                example: any
              captchaText:
                example: any
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
  /get-country-list:
    get:
      security:
        - Bearer: []
      tags: []
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /resend-otp:
    post:
      tags:
        - User
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              email:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /forgot-password:
    post:
      tags:
        - User
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              email:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /my-profile:
    post:
      security:
        - Bearer: []
      tags:
        - User
      description: ''
      parameters:
        - name: userNum
          in: query
          type: string
        - name: obj
          in: body
          schema:
            type: object
            properties:
              userNum:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error 
  /update-profile:
    post:
      security:
        - Bearer: []
      tags:
        - User
      description: ''
      parameters:
        - name: userNum
          in: query
          type: string
        - name: obj
          in: body
          schema:
            type: object
            properties:
              firstName:
                example: any
              lastName:
                example: any
              dateOfBirth:
                example: any
              gender:
                example: any
              email:
                example: any
              mobileNo:
                example: any
              preferredLanguage:
                example: any
              district:
                example: any
              country:
                example: any
              age:
                example: any 
              userNum:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
  /get-secure-cap:
    get:
      tags: []
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /verify-secure-cap:
    post:
      tags: []
      description: ''
      parameters:
        - name: obj
          in: body
          schema:
            type: object
            properties:
              secureId:
                example: any
              captchaText:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /verify-user:
    post:
      tags:
        - User
      description: ''
      parameters:
        - name: userName
          in: body
          description: media type
          required: true
          schema:
            type: string
            example: name
      responses:
        '200':
          description: OK
  /media/{type}:
    post:
      security:
        - Bearer: []
      tags:
        - Contribution
      description: Endpoint to get media for contribution
      parameters:
        - name: type
          in: path
          required: true
          type: string
          description: media type
        - name: userNum
          in: query
          type: string
        - name: obj
          in: body
          description: User info
          required: true
          schema:
            type: object
            properties:
              userName:
                type: string
                example: name
              language:
                type: string
                example: Hindi
              toLanguage:
                type: string
                example: English
              age:
                type: string
                example: upto 10
        - name: userId
          in: header
          type: string
          description: user id header
          required: true
      responses:
        '200':
          description: response data
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    dataset_row_id:
                      type: string
                      example: '123'
                    media_data:
                      type: string
                      example: qwe
                    source_info:
                      type: string
                      example: abc
            xml:
              name: main
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /contributions/{type}/{userNum}:
    get:
      security:
        - Bearer: []
      tags:
        - Validation
      description: >-
        Endpoint to get contributed data for validation. parameter "to" is only
        required if type=parallel.
      parameters:
        - name: type
          in: path
          required: true
          type: string
          description: media type
        - name: userNum
          in: path
          required: true
          type: string
        - name: from
          in: query
          type: string
          description: From language
          required: true
        - name: to
          in: query
          type: string
          description: To language
          required: true
        - name: username
          in: query
          type: string
        - name: platformId
          in: query
          type: string
        - name: userId
          in: header
          type: string
          description: user id header
          required: true
        - name: obj
          in: body
          schema:
            type: object
            properties:
              userNum:
                example: any
      responses:
        '200':
          description: response data
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    contribution_id:
                      type: string
                      example: '123'
                    dataset_row_id:
                      type: number
                      example: 321
                    sentence:
                      type: string
                      example: Text 1
                    contribution:
                      type: string
                      example: contribution/1
                    source_info:
                      type: string
                      example: info
            xml:
              name: main
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /validate/{contributionId}/{action}:
    post:
      security:
        - Bearer: []
      tags:
        - Validation
      description: Endpoint to store validation for a contributed data.
      parameters:
        - name: contributionId
          in: path
          required: true
          type: string
        - name: action
          in: path
          required: true
          type: string
          description: Validation action taken (accept/reject/skip)
        - name: userNum
          in: query
          type: string
        - name: userId
          in: header
          type: string
          description: user id header
          required: true
        - name: obj
          in: body
          description: Validation details
          required: true
          schema:
            type: object
            properties:
              sentenceId:
                type: number
                example: 1123
              state:
                type: string
                example: Punjab
              country:
                type: string
                example: India
              userName:
                type: string
                example: name
              device:
                type: string
                example: device
              browser:
                type: string
                example: browser_name
              type:
                type: string
                example: asr
              fromLanguage:
                type: string
                example: Hindi
              language:
                type: string
                example: English
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Unprocessable Entity
  /skip:
    post:
      security:
        - Bearer: []
      tags:
        - Contribution
      description: Endpoint to mark contribution as skipped
      parameters:
        - name: userNum
          in: query
          type: string
        - name: userId
          in: header
          type: string
          description: user id header
          required: true
        - name: obj
          in: body
          required: true
          schema:
            type: object
            properties:
              language:
                type: string
                example: Hindi
              sentenceId:
                type: number
                example: 123
              userName:
                type: string
                example: name
              fromLanguage:
                type: string
                example: English
              state_region:
                type: string
                example: Punjab
              country:
                type: string
                example: India
              device:
                type: string
                example: deviceName
              browser:
                type: string
                example: browserName
              type:
                type: string
                example: parallel
      responses:
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: Too Many Requests
  /store:
    post:
      security:
        - Bearer: []
      tags:
        - Contribution
      description: Endpoint to store contribution data
      parameters:
        - name: userNum
          in: query
          type: string
        - name: userId
          in: header
          type: string
          description: user id header
          required: true
        - name: obj
          in: body
          required: true
          schema:
            type: object
            properties:
              sentenceId:
                type: number
                example: 123
              audioDuration:
                type: number
                example: 3
              userInput:
                type: string
                example: text contribution sentence
              speakerDetails:
                type: object
                properties:
                  userName:
                    type: string
                    example: name
                  motherTongue:
                    type: string
                    example: Hindi
                  gender:
                    type: string
                    example: Male
                  age:
                    type: string
                    example: upto 10
              language:
                type: string
                example: Hindi
              state:
                type: string
                example: Punjab
              country:
                type: string
                example: India
              device:
                type: string
                example: deviceName
              browser:
                type: string
                example: browserName
              type:
                type: string
                example: parallel
              fromLanguage:
                type: string
                example: English
      responses:
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden





